name: build
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-10

    steps:
      - run: Set-ExecutionPolicy AllSigned
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) 
      - run: @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command " [System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
      - run: choco
      - run: choco install llvm
      - uses: actions/checkout@v2
      - run: choco install ninja 
      - run: sudo apt-get update
      - run: sudo apt-get install libclang-15-dev
      - run: sudo apt-get install cmake
      - run: cmake -B build -GNinja -DCMAKE_CXX_COMPILER=clang++-15
      - run: sudo cmake --build build
      - run: ls
      - uses: actions/upload-artifact@v3
        with:
          name: jakt
          path: jakt.tar.gz
